In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('east.csv', header=None)

In [3]:
Data = np.array(df.iloc[:,:])

In [4]:
X_train = Data[:, :-1]

In [5]:
D_train = Data[:,-1]

In [6]:
class Model:
    def __init__(self, data):
        self.w = np.zeros(len(data[0])-1, dtype=np.float32)
        self.theta = 0
        self.rate = 0.1
    
    def error_correction(self, X_train, D_train):
        flag = False
        while not flag:
            wrong_count = 0
            for i in range(len(X_train)):
                x = X_train[i]
                d = D_train[i]
                print(x, d)
                output = 1 if (np.dot(x, self.w) >= self.theta) else 0
                if d != output:
                    self.w = self.w + self.rate*np.dot(d - output, x)
                    self.theta = self.theta + self.rate*(output - d)
                    wrong_count += 1
            if wrong_count == 0:
                flag = True
    
    def score(self, x_test):
        return 1 if (np.dot(x_test, self.w) >= self.theta) else 0

In [7]:
perceptron = Model(Data)
perceptron.error_correction(X_train, D_train)

(array([0, 0, 1, 0, 0, 0, 0, 0]), 1)
(array([0, 1, 0, 0, 0, 0, 0, 0]), 1)
(array([0, 0, 0, 0, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 1, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 1, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 0, 0, 0, 0]), 1)
(array([0, 1, 0, 0, 0, 0, 0, 0]), 1)
(array([0, 0, 0, 0, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 1, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 1, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 0, 0, 0, 0]), 1)
(array([0, 1, 0, 0, 0, 0, 0, 0]), 1)
(array([0, 0, 0, 0, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 1, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 1, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 0, 0, 0, 0]), 1)
(array([0, 1, 0, 0, 0, 0, 0, 0]), 1)
(array([0, 0, 0, 0, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 1, 0, 0, 0, 0]), 0)
(array([0, 0, 1, 0, 1, 0, 0, 0]), 0)
(array([0, 1, 1, 1, 0, 0, 0, 0]), 0)
(

In [8]:
sense = [1,1,1,0,1,1,1,0]
perceptron.score(sense)

0